org: henriqueweiand
app: nestjs-lambda-qrcode-generator
service: lambda-s3

useDotenv: true

plugins:
  - serverless-s3-local
  - serverless-offline

custom:
  s3:
    host: localhost

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: qr-codes

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
