org: henriqueweiand
app: nestjs-lambda-qrcode-generator
service: lambda-s3

useDotenv: true

plugins:
  - serverless-s3-local
  - serverless-offline

custom:
  s3:
    host: localhost

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::qr-codes
        - arn:aws:s3:::qr-codes/*
  environment:
    accessKeyId: ${env:accessKeyId}
    secretAccessKey: ${env:secretAccessKey}
    endpoint: ${env:endpoint}
    bucket: ${env:bucket}
    NODE_ENV: ${env:NODE_ENV}

# resources:
#   Resources:
#     NewResource:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${env:bucket}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
